version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=restusers
      - POSTGRES_USER=migratusr
      - POSTGRES_PASSWORD=migratusr
      - POSTGRES_SCHEMA=public
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres/init:/docker-entrypoint-initdb.d/