CREATE TABLE IF NOT EXISTS users
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    firstname   VARCHAR(255) NOT NULL,
    surname     VARCHAR(255) NOT NULL,
    "login"     VARCHAR(255) NOT NULL,
    "password"  VARCHAR(255) NOT NULL,
    description VARCHAR(300) NOT NULL,
    address     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS users
    OWNER to migratusr;

INSERT INTO public.users (firstname, surname, "login", "password", description, address)
VALUES ('Test name', 'Test surname', 'Test login', 'passwrd', 'discr', 'addrs');